"""Добавлено автоматическое значение для participant, team, submission

Revision ID: 103ecaa86fff
Revises: 16dfec4aa348
Create Date: 2024-04-25 21:25:48.727941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '103ecaa86fff'
down_revision: Union[str, None] = '16dfec4aa348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'registration_date', server_default=sa.func.now())
    op.alter_column('teams', 'creation_date', server_default=sa.func.now())
    op.alter_column('submissions', 'submission_date', server_default=sa.func.now())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'registration_date', server_default=None)
    op.alter_column('teams', 'creation_date', server_default=None)
    op.alter_column('submissions', 'submission_date', server_default=None)
    # ### end Alembic commands ###
