"""Добавлено автоматическое значение для publication_date

Revision ID: 16dfec4aa348
Revises:
Create Date: 2024-04-24 23:26:31.539459

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '16dfec4aa348'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'publication_date', server_default=sa.func.now())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'publication_date', server_default=None)
    # ### end Alembic commands ###
